export const products = {
  listOfHearders: null,
  listOfRowData: null,
  listOfRowWithKeyValues: [
    {
      Sku_Id: "344622",
      Sku_Code: "sc1",
      Sku_Name: "sn1",
      ProductHierarchyLevel1: "c1",
      ProductHierarchyLevel2: "ss1",
      ProductHierarchyLevel3: "sub1",
      ProductHierarchyLevel4: "sss1",
      ProductHierarchyLevel5: "ssss1",
      Location_Code: "lc1",
      Location_Name: "ln1",
      Sale_Price_Unit: "16.22",
    },
    {
      Sku_Id: "344628",
      Sku_Code: "sc2",
      Sku_Name: "sn2",
      ProductHierarchyLevel1: "c2",
      ProductHierarchyLevel2: "ss2",
      ProductHierarchyLevel3: "sub2",
      ProductHierarchyLevel4: "sss2",
      ProductHierarchyLevel5: "ssss2",
      Location_Code: "lc2",
      Location_Name: "ln2",
      Sale_Price_Unit: "16.46",
    },
    {
      Sku_Id: "344634",
      Sku_Code: "sc3",
      Sku_Name: "sn3",
      ProductHierarchyLevel1: "c3",
      ProductHierarchyLevel2: "ss3",
      ProductHierarchyLevel3: "sub3",
      ProductHierarchyLevel4: "sss3",
      ProductHierarchyLevel5: "ssss3",
      Location_Code: "lc3",
      Location_Name: "ln3",
      Sale_Price_Unit: "6.69",
    },
    {
      Sku_Id: "344640",
      Sku_Code: "sc4",
      Sku_Name: "sn4",
      ProductHierarchyLevel1: "c4",
      ProductHierarchyLevel2: "ss4",
      ProductHierarchyLevel3: "sub4",
      ProductHierarchyLevel4: "sss4",
      ProductHierarchyLevel5: "ssss4",
      Location_Code: "lc4",
      Location_Name: "ln4",
      Sale_Price_Unit: "7.92",
    },
    {
      Sku_Id: "344646",
      Sku_Code: "sc5",
      Sku_Name: "sn5",
      ProductHierarchyLevel1: "c5",
      ProductHierarchyLevel2: "ss5",
      ProductHierarchyLevel3: "sub5",
      ProductHierarchyLevel4: "sss5",
      ProductHierarchyLevel5: "ssss5",
      Location_Code: "lc5",
      Location_Name: "ln5",
      Sale_Price_Unit: "9.16",
    },
    {
      Sku_Id: "344652",
      Sku_Code: "sc6",
      Sku_Name: "sn6",
      ProductHierarchyLevel1: "c6",
      ProductHierarchyLevel2: "ss6",
      ProductHierarchyLevel3: "sub6",
      ProductHierarchyLevel4: "sss6",
      ProductHierarchyLevel5: "ssss6",
      Location_Code: "lc6",
      Location_Name: "ln6",
      Sale_Price_Unit: "10.39",
    },
    {
      Sku_Id: "344658",
      Sku_Code: "sc7",
      Sku_Name: "sn7",
      ProductHierarchyLevel1: "c7",
      ProductHierarchyLevel2: "ss7",
      ProductHierarchyLevel3: "sub7",
      ProductHierarchyLevel4: "sss7",
      ProductHierarchyLevel5: "ssss7",
      Location_Code: "lc7",
      Location_Name: "ln7",
      Sale_Price_Unit: "11.62",
    },
    {
      Sku_Id: "344664",
      Sku_Code: "sc8",
      Sku_Name: "sn8",
      ProductHierarchyLevel1: "c8",
      ProductHierarchyLevel2: "ss8",
      ProductHierarchyLevel3: "sub8",
      ProductHierarchyLevel4: "sss8",
      ProductHierarchyLevel5: "ssss8",
      Location_Code: "lc8",
      Location_Name: "ln8",
      Sale_Price_Unit: "12.86",
    },
    {
      Sku_Id: "344670",
      Sku_Code: "sc9",
      Sku_Name: "sn9",
      ProductHierarchyLevel1: "c9",
      ProductHierarchyLevel2: "ss9",
      ProductHierarchyLevel3: "sub9",
      ProductHierarchyLevel4: "sss9",
      ProductHierarchyLevel5: "ssss9",
      Location_Code: "lc9",
      Location_Name: "ln9",
      Sale_Price_Unit: "14.09",
    },
    {
      Sku_Id: "344676",
      Sku_Code: "sc10",
      Sku_Name: "sn10",
      ProductHierarchyLevel1: "c10",
      ProductHierarchyLevel2: "ss10",
      ProductHierarchyLevel3: "sub10",
      ProductHierarchyLevel4: "sss10",
      ProductHierarchyLevel5: "ssss10",
      Location_Code: "lc10",
      Location_Name: "ln10",
      Sale_Price_Unit: "15.33",
    },
    {
      Sku_Id: "344682",
      Sku_Code: "sc11",
      Sku_Name: "sn11",
      ProductHierarchyLevel1: "c11",
      ProductHierarchyLevel2: "ss11",
      ProductHierarchyLevel3: "sub11",
      ProductHierarchyLevel4: "sss11",
      ProductHierarchyLevel5: "ssss11",
      Location_Code: "lc11",
      Location_Name: "ln11",
      Sale_Price_Unit: "16.56",
    },
    {
      Sku_Id: "344688",
      Sku_Code: "sc12",
      Sku_Name: "sn12",
      ProductHierarchyLevel1: "c12",
      ProductHierarchyLevel2: "ss12",
      ProductHierarchyLevel3: "sub12",
      ProductHierarchyLevel4: "sss12",
      ProductHierarchyLevel5: "ssss12",
      Location_Code: "lc12",
      Location_Name: "ln12",
      Sale_Price_Unit: "17.79",
    },
    {
      Sku_Id: "344694",
      Sku_Code: "sc13",
      Sku_Name: "sn13",
      ProductHierarchyLevel1: "c13",
      ProductHierarchyLevel2: "ss13",
      ProductHierarchyLevel3: "sub13",
      ProductHierarchyLevel4: "sss13",
      ProductHierarchyLevel5: "ssss13",
      Location_Code: "lc13",
      Location_Name: "ln13",
      Sale_Price_Unit: "19.03",
    },
    {
      Sku_Id: "344700",
      Sku_Code: "sc14",
      Sku_Name: "sn14",
      ProductHierarchyLevel1: "c14",
      ProductHierarchyLevel2: "ss14",
      ProductHierarchyLevel3: "sub14",
      ProductHierarchyLevel4: "sss14",
      ProductHierarchyLevel5: "ssss14",
      Location_Code: "lc14",
      Location_Name: "ln14",
      Sale_Price_Unit: "20.26",
    },
    {
      Sku_Id: "344706",
      Sku_Code: "sc15",
      Sku_Name: "sn15",
      ProductHierarchyLevel1: "c15",
      ProductHierarchyLevel2: "ss15",
      ProductHierarchyLevel3: "sub15",
      ProductHierarchyLevel4: "sss15",
      ProductHierarchyLevel5: "ssss15",
      Location_Code: "lc15",
      Location_Name: "ln15",
      Sale_Price_Unit: "21.49",
    },
    {
      Sku_Id: "344712",
      Sku_Code: "sc16",
      Sku_Name: "sn16",
      ProductHierarchyLevel1: "c16",
      ProductHierarchyLevel2: "ss16",
      ProductHierarchyLevel3: "sub16",
      ProductHierarchyLevel4: "sss16",
      ProductHierarchyLevel5: "ssss16",
      Location_Code: "lc16",
      Location_Name: "ln16",
      Sale_Price_Unit: "22.73",
    },
    {
      Sku_Id: "344718",
      Sku_Code: "sc17",
      Sku_Name: "sn17",
      ProductHierarchyLevel1: "c17",
      ProductHierarchyLevel2: "ss17",
      ProductHierarchyLevel3: "sub17",
      ProductHierarchyLevel4: "sss17",
      ProductHierarchyLevel5: "ssss17",
      Location_Code: "lc17",
      Location_Name: "ln17",
      Sale_Price_Unit: "23.96",
    },
    {
      Sku_Id: "344724",
      Sku_Code: "sc18",
      Sku_Name: "sn18",
      ProductHierarchyLevel1: "c18",
      ProductHierarchyLevel2: "ss18",
      ProductHierarchyLevel3: "sub18",
      ProductHierarchyLevel4: "sss18",
      ProductHierarchyLevel5: "ssss18",
      Location_Code: "lc18",
      Location_Name: "ln18",
      Sale_Price_Unit: "25.2",
    },
    {
      Sku_Id: "344730",
      Sku_Code: "sc19",
      Sku_Name: "sn19",
      ProductHierarchyLevel1: "c19",
      ProductHierarchyLevel2: "ss19",
      ProductHierarchyLevel3: "sub19",
      ProductHierarchyLevel4: "sss19",
      ProductHierarchyLevel5: "ssss19",
      Location_Code: "lc19",
      Location_Name: "ln19",
      Sale_Price_Unit: "26.43",
    },
    {
      Sku_Id: "344736",
      Sku_Code: "sc20",
      Sku_Name: "sn20",
      ProductHierarchyLevel1: "c20",
      ProductHierarchyLevel2: "ss20",
      ProductHierarchyLevel3: "sub20",
      ProductHierarchyLevel4: "sss20",
      ProductHierarchyLevel5: "ssss20",
      Location_Code: "lc20",
      Location_Name: "ln20",
      Sale_Price_Unit: "27.66",
    },
    {
      Sku_Id: "344742",
      Sku_Code: "sc21",
      Sku_Name: "sn21",
      ProductHierarchyLevel1: "c21",
      ProductHierarchyLevel2: "ss21",
      ProductHierarchyLevel3: "sub21",
      ProductHierarchyLevel4: "sss21",
      ProductHierarchyLevel5: "ssss21",
      Location_Code: "lc21",
      Location_Name: "ln21",
      Sale_Price_Unit: "28.9",
    },
  ],
  pageIndex: 1,
  pageSize: 10,
  totalElements: 21,
  totalPages: 1,
};
