//Product Types
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const UPLOAD_PRODUCT_CSV_DATA = "UPLOAD_PRODUCT_CSV_DATA";
export const UPLOAD_PRODUCT_CSV_DATA_INITIATE = "UPLOAD_PRODUCT_CSV_DATA_INITIATE";
export const UPLOAD_PRODUCT_CSV_DATA_COMPLETE = "UPLOAD_PRODUCT_CSV_DATA_COMPLETE";

//Pesonal Type
export const GET_ALL_PERSONNEL = "GET_ALL_PERSONNEL";
export const UPLOAD_PERSONNEL_CSV_DATA = "UPLOAD_PERSONNEL_CSV_DATA";
export const UPLOAD_PERSONNEL_CSV_DATA_INITIATE = "UPLOAD_PERSONNEL_CSV_DATA_INITIATE";
export const UPLOAD_PERSONNEL_CSV_DATA_COMPLETE = "UPLOAD_PERSONNEL_CSV_DATA_COMPLETE";
//SNOP Types
export const GET_ALL_SNOP = "GET_ALL_SNOP";
